### ISSUE TITLE
 InvokeMethod does not work with dict

### ISSUE THREAD

**Issue by bernardx** [CefView/QCefView#49]
**Describe the bug**
Dict info lost during message dispatch

**To Reproduce**
Call 'InvokeMethod' with a dict object:
`
ret = {data:"test"};
window.CallBridge.invokeMethod('TestMethod',ret)
`
Then a callback is triggered in  'MainWindow::onInvokeMethod', in this callback, I got a QVariantMap with the 'data' key, but the 'test' value was lost.

Further invistgate,  in 'CefValueToQVariant',  I got 'CefValueType::VTYPE_NULL' while deserializing the dict object.
However, in the 'V8ValueToCefValue' function, those values do exist.
So it seems dict content has been lost during SendProcessMessage, I cannot figure out why.

**Comment by tishion** [comment]
Hi @bernardx  thanks for your help. 
This was caused by the bugs in arguments conversion between CefValue and V8Value in CefViewCore module
Fixed already, CefViewCore: https://github.com/CefView/CefViewCore/commit/5db8a8d6982c8429fd81ae79ef297220f54b8d1d

Also update core and enrich the test case in QCefView:  https://github.com/CefView/QCefView/commit/f04a406be4c1657ba6f140464bae33869812a747

**Comment by bernardx** [comment]
Appreciate your quick response.
I didn't notice the typo between v8Value and v8Val either. 😂
